In [1]:
#!pip install pyforest

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import sys
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('Bank_churn_modelling.csv')
df.head(2)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   

   Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.00              1          1               1   
1       1  83807.86              1          0               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
df.describe(include = 'all').T

count unique     top  freq           mean           std  \
RowNumber        10000.0    NaN     NaN   NaN         5000.5    2886.89568   
CustomerId       10000.0    NaN     NaN   NaN  15690940.5694  71936.186123   
Surname            10000   2932   Smith    32            NaN           NaN   
CreditScore      10000.0    NaN     NaN   NaN       650.5288     96.653299   
Geography          10000      3  France  5014            NaN           NaN   
Gender             10000      2    Male  5457            NaN           NaN   
Age              10000.0    NaN     NaN   NaN        38.9218     10.487806   
Tenure           10000.0    NaN     NaN   NaN         5.0128      2.892174   
Balance          10000.0    NaN     NaN   NaN   76485.889288  62397.405202   
NumOfProducts    10000.0    NaN     NaN   NaN         1.5302      0.581654   
HasCrCard        10000.0    NaN     NaN   NaN         0.7055       0.45584   
IsActiveMember   10000.0    NaN     NaN   NaN         0.5151      0.499797   
EstimatedSalary  10000.0    NaN     NaN   NaN  100090.239881  57510.492818   
Exited           10000.0    NaN     NaN   NaN         0.2037      0.402769   

                        min          25%         50%          75%         max  
RowNumber               1.0      2500.75      5000.5      7500.25     10000.0  
CustomerId       15565701.0  15628528.25  15690738.0  15753233.75  15815690.0  
Surname                 NaN          NaN         NaN          NaN         NaN  
CreditScore           350.0        584.0       652.0        718.0       850.0  
Geography               NaN          NaN         NaN          NaN         NaN  
Gender                  NaN          NaN         NaN          NaN         NaN  
Age                    18.0         32.0        37.0         44.0        92.0  
Tenure                  0.0          3.0         5.0          7.0        10.0  
Balance                 0.0          0.0    97198.54    127644.24   250898.09  
NumOfProducts           1.0          1.0         1.0          2.0         4.0  
HasCrCard               0.0          0.0         1.0          1.0         1.0  
IsActiveMember          0.0          0.0         1.0          1.0         1.0  
EstimatedSalary       11.58     51002.11  100193.915  149388.2475   199992.48  
Exited                  0.0          0.0         0.0          0.0         1.0

In [6]:
df=df.drop(['RowNumber', 'CustomerId', 'Surname'],axis=1)

In [7]:
'''cat=["Geography","Gender","HasCrCard","IsActiveMember","Exited"]
con=['CreditScore',"Tenure","Balance",'NumOfProducts',"EstimatedSalary","Age"]
for i in cat:
    sns.countplot(x=i,data=df)
    plt.show()'''

'cat=["Geography","Gender","HasCrCard","IsActiveMember","Exited"]\ncon=[\'CreditScore\',"Tenure","Balance",\'NumOfProducts\',"EstimatedSalary","Age"]\nfor i in cat:\n    sns.countplot(x=i,data=df)\n    plt.show()'

In [8]:
'''for i in con:
    sns.distplot(df[i])
    plt.show()'''

'for i in con:\n    sns.distplot(df[i])\n    plt.show()'

In [9]:
'''sns.countplot(x="Gender",hue="Exited",data=df)
plt.show()'''

'sns.countplot(x="Gender",hue="Exited",data=df)\nplt.show()'

In [10]:
'''sns.barplot(x="Geography",y="Exited",data=df)
plt.show()'''

'sns.barplot(x="Geography",y="Exited",data=df)\nplt.show()'

In [11]:
'''sns.distplot(df["CreditScore"][df["Exited"]==1],color='r')
sns.distplot(df["CreditScore"][df["Exited"]==0],color='g')
plt.show()'''

'sns.distplot(df["CreditScore"][df["Exited"]==1],color=\'r\')\nsns.distplot(df["CreditScore"][df["Exited"]==0],color=\'g\')\nplt.show()'

In [12]:
'''df.info()'''

'df.info()'

In [13]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Geography']=encoder.fit_transform(df['Geography'])
df['Gender']= encoder.fit_transform(df['Gender'])
'''onehotencoder = OneHotEncoder()
x = onehotencoder.fit_transform(x).toarray()
x = x[:,1:]'''

'onehotencoder = OneHotEncoder()\nx = onehotencoder.fit_transform(x).toarray()\nx = x[:,1:]'

In [14]:
# logistic regression
#a = ['CreditScore','Geography','Gender','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary']
x = df.drop(['Exited'],axis = 1)
y = df[['Exited']]
print(x)
print(y)

      CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619          0       0   42       2       0.00              1   
1             608          2       0   41       1   83807.86              1   
2             502          0       0   42       8  159660.80              3   
3             699          0       0   39       1       0.00              2   
4             850          2       0   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771          0       1   39       5       0.00              2   
9996          516          0       1   35      10   57369.61              1   
9997          709          0       0   36       7       0.00              1   
9998          772          1       1   42       3   75075.31              2   
9999          792          0       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  


In [15]:
x.shape

(10000, 10)

In [16]:
y.shape

(10000, 1)

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,train_size=0.8,random_state=42)

In [19]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8000 entries, 9254 to 7270
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      8000 non-null   int64  
 1   Geography        8000 non-null   int32  
 2   Gender           8000 non-null   int32  
 3   Age              8000 non-null   int64  
 4   Tenure           8000 non-null   int64  
 5   Balance          8000 non-null   float64
 6   NumOfProducts    8000 non-null   int64  
 7   HasCrCard        8000 non-null   int64  
 8   IsActiveMember   8000 non-null   int64  
 9   EstimatedSalary  8000 non-null   float64
dtypes: float64(2), int32(2), int64(6)
memory usage: 625.0 KB


In [20]:
x_test.shape

(2000, 10)

In [21]:
y_test.shape

(2000, 1)

In [22]:
df.Geography.unique()

array([0, 2, 1])

In [23]:
x.shape

(10000, 10)

In [24]:
y.shape

(10000, 1)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  int32  
 2   Gender           10000 non-null  int32  
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64  
dtypes: float64(2), int32(2), int64(7)
memory usage: 781.4 KB


In [26]:
df['Exited'].unique()

array([1, 0], dtype=int64)

In [27]:
type(x_test)

pandas.core.frame.DataFrame

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [29]:
df.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [30]:
#df['Geography'] = df.Geography.astype(float)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  int32  
 2   Gender           10000 non-null  int32  
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64  
dtypes: float64(2), int32(2), int64(7)
memory usage: 781.4 KB


In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
model= LogisticRegression()
print(model.fit(x_train,y_train))
y_pred=model.predict(x_test)
print('Accuracy: ', accuracy_score(y_test, y_pred))
plt.show()

LogisticRegression()
Accuracy:  0.815


In [33]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print('accuracy score :' ,accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.97      0.89      1607
           1       0.60      0.18      0.28       393

    accuracy                           0.81      2000
   macro avg       0.71      0.58      0.59      2000
weighted avg       0.78      0.81      0.77      2000

[[1559   48]
 [ 322   71]]
accuracy score : 0.815


In [34]:
from sklearn.ensemble import RandomForestClassifier as rfc
rfc_object = rfc(n_estimators=100,max_depth= 5, random_state = 1)
rfc_object.fit(x_train, y_train)
predicted_labels = rfc_object.predict(x_test)

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(classification_report(y_test, predicted_labels))
print(confusion_matrix(y_test, predicted_labels))
print(accuracy_score(y_test,predicted_labels))

              precision    recall  f1-score   support

           0       0.86      0.98      0.92      1607
           1       0.83      0.35      0.49       393

    accuracy                           0.86      2000
   macro avg       0.84      0.67      0.70      2000
weighted avg       0.85      0.86      0.83      2000

[[1578   29]
 [ 256  137]]
0.8575


In [36]:
print(rfc_object.score(x_test,y_test)*100)
print(rfc_object.score(x_train,y_train)*100)
#print(accuracy_score(y_test,predicted_labels))

85.75
85.91250000000001


In [37]:
#pip install xgboost

In [38]:
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.metrics import mean_squared_error,accuracy_score
#data_dmatrix = xgb.DMatrix(data=x,label=y)
xg_cla = XGBClassifier(max_depth =5, n_estimators = 100)
xg_cla.fit(x_train,y_train)
preds1 = xg_cla.predict(x_test)
predictions1 = [round(value) for value in preds1]
rmse = np.sqrt(mean_squared_error(y_test, predictions1))
print("RMSE: %f" % (rmse))
accuracy = accuracy_score(y_test, predictions1)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

[22:20:09] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
RMSE: 0.373497
Accuracy: 86.05%


In [39]:
import pickle
pickle.dump(model, open('model.pkl','wb'))